### ISSUE TITLE
The Buying Screen Data Is Not "Live"

### ISSUE THREAD

**Issue by Daves10** [hunterjm/fifa-autobuyer#107]
Hi again jason, this app keeps getting better and better!

However I noticed that the Buying screen does not show the actual value and i think this is causing problems in the re-bidding process.

For instance, if I change the screen from Current to Logs and then go back, the "Expires" number on the buying screen always go back to a certain value, which shows this is not "live" data. I don´t know if I made myself clear..

I'm getting a lot of 461 errors such as:
"futApiStatusCode": 461,
  "reason": "You are not allowed to bid on this trade"

{
  "futApiStatusCode": 461,
  "reason": "Permission Denied"
}

I'm guessing this is related to the problem above as I have enough credits and no number of card limitations, and the current bid (and supposedly the final bid) are below my Max Price

**Comment by hunterjm** [comment]
The Overview screen starts the countdown from the time EA provides, and only updates when we check the auctions again.  It's always updating, but not every second, because that would get you banned.  It gets updated as the Autobuyer makes it's way though the bidding cycle, but I have definitely prioritized actually bidding on cards and winning auctions over updating the Overview display. 

461 usually means that somebody beat you to the bid on that player.  Not really related.  If the final bid is below your max price, it means the AB tried to search the player, but there is a delay between the search and the bid (varies based on your RPM).  It is completely possible for someone to place a bid in between that time and for the auction to expire before we get back to it in the next cycle.

**Comment by Daves10** [comment]
OK got it. I'm with a low RPM so that could be the cause of it.

How long does it take between automatic update prices, 1 hour? Can we make it shorter?
I think it should be lower as if I update the price manually I see that the price went down and that I'm willing to buy the player at a higher price.

**Comment by hunterjm** [comment]
I can probably add the update interval as a global setting.

**Comment by Daves10** [comment]
Sure! thanks!
