### ISSUE TITLE
Question: How is my account information being stored?

### ISSUE THREAD

**Issue by TJGames97** [hunterjm/fifa-autobuyer#108]
Thank you for your effort to make this program, seems to work perfectly so far. I'm just wondering how my account data is being stored. Thanks for your time!

**Comment by hunterjm** [comment]
This app uses Electron, which is a way to use web technologies on the desktop.  At it's core, it is just a self contained Chrome browser window with some additional features.  Since at it's core, this app runs in Chrome, we use local storage to save your account information, player list, bidding history, and settings.  It remains on your local computer, and only gets sent out to EA's servers to log you in and create a session.  You can see what we save here: https://github.com/hunterjm/fifa-autobuyer/blob/master/app/middleware/persist.js

**Comment by TJGames97** [comment]
Fantastic, and thanks for getting back to me so quickly. Also, it appears that someone is selling your program on eBay... Not sure if you can do anything about it, but you should probably have your name somewhere obvious in the program as well as a link to donate or something. Just a suggestion, but otherwise, thank you!

**Comment by hunterjm** [comment]
That's funny.  Do you have a link to the auction?  Technically, I licensed this software under [MIT](https://github.com/hunterjm/fifa-autobuyer/blob/master/LICENSE), which means anybody who obtains a copy is free to do with it what they want so long as they provide a copy of the MIT license with it.

**Comment by TJGames97** [comment]
http://www.ebay.com/itm/FIFA-17-Ultimate-Team-Autobuyer-PREMIUM-AUTO-UPDATING-/112295072624?hash=item1a254ed370:g:FuAAAOSw9GhYmN83 I see, just want to make sure you get the proper acknowledgement rather than everyone else tagging their name onto it.

**Comment by hunterjm** [comment]
I appreciate it.
