### ISSUE TITLE
Suggestion to improve the bidding when error 461 occurs

### ISSUE THREAD

**Issue by daniele85** [hunterjm/fifa-autobuyer#143]
I noticed that when error 461 occurs the auction is then lost almost all the times. I think that this is due to the fact that somebody else has already placed a bid higher than the bot, during the time between operations, which is quite high unless one increases the RPM a lot.

Maybe a good strategy could be that, right after a 461, the bot looks immediately (bypassing the rpm cycle) for the current bid and places immediately an appropriate bid?

What do you think, @hunterjm ?

**Comment by mestesso93** [comment]
in my hopinion this feature make a serious risk of ban

**Comment by daniele85** [comment]
yes that's possible, maybe an intermediate solution would be to give priority to the auction that gets a 461, in the sense that the next action of the bot (while respecting the rpm time) would be to update *that* auction and then bid on that. This shouldn't make a huge difference in terms of risk of ban, since the action would be delayed normally, it would just get priority with respect to other actions that the bot wants to perform...

**Comment by hunterjm** [comment]
This should actually be fixed in the latest version as well. Right before a bid action is made, we immediately refresh the current status of the trade.

The AB still waits based on the RPM before attempting to bid, but the current price is updated. The Web app already does this, so we should be ok on the ban front.
