### ISSUE TITLE
[Request] Better detail for bid error 

### ISSUE THREAD

**Issue by JSystem1** [hunterjm/fifa-autobuyer#15]
Hi Hunter,

Just want to start off saying thank you so much for your effort and time working on this project I have actually started to learn python as I was that interested in the code from your gui version so thanks.

I know you understand JavaScript a lot better then python and was wondering could you include this feature if it is not to hard/time consuming, I just find if I was getting a detailed error like what that players name is, what he went for, etc.

Really keep up the good work man I really appreciate your hardwork

Regards

**Comment by hunterjm** [comment]
I wouldn't worry too much about individual bids.  In this version, I will be including a history pane that will give you high level details about the performance of somebody in your list.  It will include things like average profit, average time to sale (how long do you hold on to it after you buy it), price fluctuations (is this a pretty stable player, or does the price rise and drop a lot), etc...

It would be much more productive to focus on the macro picture in order to make sure you are maximizing your player list.
