### ISSUE TITLE
Error 456

### ISSUE THREAD

**Issue by slimbo123** [hunterjm/fifa-autobuyer#191]
new error, you have to log into the webapp and it makes you calculate a maths question.

after i calculated it and went back into autobuyer. the error appeared again. 

calculated it again, stopped using autobuyer. Got into a bidding war in the webapp and it logged me out and made me do another calculation! lost the auction too

**Comment by slimbo123** [comment]
[screenshot](https://i.redd.it/pwlsz344db3z.png)

**Comment by Jeuiskeh** [comment]
probably because they suspect you of being a bot

**Comment by slimbo123** [comment]
no its happening to normal users on reddit too, even futbin can't update fast enough due to this

**Comment by Jeuiskeh** [comment]
Yeah i've read on reddit that anyone using a rpm of 3 or higher will get this because ea is using this to get rid off people using bots as it takes way too long to quit the bot, log onto the web app do the "maths problem" and use the bot again. This is very inefficient so most botters will stop as they will be put off by this. The only way to not get the captcha is to use a very low rpm like 1-3rpm.

**Comment by Jeuiskeh** [comment]
nvm haha its fixed it was probably a bug from ea that was fixed lol

**Comment by slimbo123** [comment]
really? nice! so what RPM should we use?
thanks for keeping me updated

**Comment by Jeuiskeh** [comment]
i always use 6 rpm usually just because i use the bot to bid on items rather than BIN just never use an rpm higher than 10 in my opinion.
