### ISSUE TITLE
Stormshield Endpoint Security : Keylogging Alert

### ISSUE THREAD

**Issue by stormlolz** [hunterjm/fifa-autobuyer#22]
Hello, when I run the program on windows

![fifa try](https://cloud.githubusercontent.com/assets/20703341/22067132/31d889fc-dd90-11e6-8488-1912d35d698a.png)

I have translate the message in ENG : 

"A keylogging attempt made by fifa autobuyer.exe was blocked by Stormshield Endpoint Security"

And when I connect 

![image](https://cloud.githubusercontent.com/assets/20703341/22067091/0768879e-dd90-11e6-9ebe-c8b598237e6d.png)

**Comment by hunterjm** [comment]
Well there isn't a key logger.  If you don't believe me, you can look at the source code 😉 .  It's probably because I use localstorage to save your login information on your computer (it never leaves your machine) so you don't have to log in multiple times.  If Stormshield is blocking functionality of the app, then that is probably why the login is not working.  Can you whitelist it in your virus software?

**Comment by stormlolz** [comment]
Hello,

No I can't white list the app on my computer because I'm at work :(

But I try later with my personnal computer, thank you

**Comment by hunterjm** [comment]
Closed due to inactivity.
