### ISSUE TITLE
futApiStatusCode: 500

### ISSUE THREAD

**Issue by kledac** [hunterjm/fifa-autobuyer#26]
Hey @hunterjm. 

I'm getting this error a lot! It seems like i can't bid anyone anymore.

[22:35:18] Error placing BIN bid $750 on Consigli
{
  "futApiStatusCode": 500
}

**Comment by hunterjm** [comment]
Most likely a temporary ban.  What RPM settings are you using?  How long has it been running?  Are you able to place any bids on the [web app](https://www.easports.com/fifa/ultimate-team/web-app)?

**Comment by kledac** [comment]
I can't bid on the web app also ... probably a ban, hope not permanent...
I'll try on my console tomorrow.

**Comment by hunterjm** [comment]
Doubtful it's permanent if you can still log in and search for auctions.  If you don't mind me asking, how long did you have it running and at what RPM before you noticed the errors?  I might be able to build in some additional safeguards to automatically stop bidding after a period of time to prevent getting flagged.

**Comment by kledac** [comment]
To be honest I don't know for how long, but the RPM was at 16. Maybe three hours?
But I do know that I've set it to snipe only, so maybe something happened there.

**Comment by hunterjm** [comment]
It's probably more due to the fact that EA thinks you have been searching and sniping every 3-4 seconds for 3 hours straight. The higher the RPM, the earlier EA will issue a temp ban. The trick is finding a middle ground where it is fast enough that you win auctions, but slow enough that you don't get banned.
