### ISSUE TITLE
Price update on restart

### ISSUE THREAD

**Issue by kledac** [hunterjm/fifa-autobuyer#34]
When I started the buyer today I've notice that the prices remained the same from yesterday so it started buying some player for it's bin price, but after that the prices updated and they were lower than the BIN prices.

I think that on restart of the app the prices should be reseted so that doesn't happen and avoid some potencial coin loss.

**Comment by hunterjm** [comment]
Can you copy the session log here? Checking if prices need to be updated is one of the first things the AB does when you start bidding. It absolutely does it before buying anything. Nothing I've seen when testing suggests otherwise.

https://github.com/hunterjm/fifa-autobuyer/blob/master/app/actions/logic/index.js#L58

**Comment by hunterjm** [comment]
Closed due to inactivity.
