### ISSUE TITLE
Problem whith player name

### ISSUE THREAD

**Issue by nitramnoe** [hunterjm/fifa-autobuyer#45]
Hey, thanks a lot for your work! You're the best!
(First, sorry for my english)
I notice that when you remove the player from your "target list", his name on the bidding overview become "unknown".

I'm learning node and i'm not enough good to understand it...
I wish i will help you later.
thanks!

**Comment by hunterjm** [comment]
It's because we aren't tracking that player.  Unfortunately EA doesn't provide the player's name in the response from the watchlist or tradepile.  We look up that player from your target list, and if they don't exist, default to "Unknown".  The same would happen for any players or consumables in your tradepile that the AB is not tracking.

We could possibly do a lookup based on the ID if it doesn't exist in your target list, but it should handle re-listing and removing them from the watchlist and tradepile automatically either way.
